id: P003051
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4927
  title: ཞལ་ཐང་འབྲི་ཐབས་ཀུན་བཟང་རྣམ་པར་རོལ་པའི་ཕྱག་རྒྱ།
  author: ''
  volumes:
    fda9e913f2f84404895c8b2c7e5c9360:
      image_group_id: I1KG5039
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
